### ISSUE TITLE
Missing shell script

### ISSUE THREAD

**Issue by Ahmedfour** [hajzer/streamer-web#2]
i would like to thanks you for your effort.
the following shell scripts are missing:
/etc/dvblast/scripts/streamer-control.sh
/etc/dvblast/scripts/streamer-scan.sh
/etc/dvblast/scripts/streamer-status.sh
/etc/dvblast/scripts/streamer-activedevices.sh
Thanks in Advance

**Comment by hajzer** [comment]
Hi. You can find the scripts in the repository https://github.com/hajzer/streamer-etc.
